spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/neosrate}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

api.security.token.secret=${API_SECURITY_TOKEN_SECRET:change-me}

aws.access.key=${AWS_ACCESS_KEY:}
aws.secret.key=${AWS_SECRET_KEY:}
aws.s3.bucket=${AWS_S3_BUCKET:neosrate}

# Upload de arquivos
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
